FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ./src/OrderProcessing.Api/OrderProcessing.Api.csproj ./src/OrderProcessing.Api/
RUN dotnet restore ./src/OrderProcessing.Api/OrderProcessing.Api.csproj

COPY . .
RUN dotnet publish ./src/OrderProcessing.Api/OrderProcessing.Api.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ENTRYPOINT ["dotnet", "OrderProcessing.Api.dll"]
